name: lets_chat
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^2.4.0

  firebase_auth: ^4.1.3

  google_sign_in: ^5.4.2

  cloud_firestore: ^4.1.0

  cached_network_image: ^3.2.3

  image_picker: ^0.8.6

  firebase_storage: ^11.0.6

  emoji_picker_flutter: ^1.5.1

  firebase_messaging: ^14.2.0

  http: ^0.13.5

  flutter_notification_channel: ^2.0.0

  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#   flutter_launcher_icons: "^0.11.0"

# flutter_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "images/chat.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   remove_alpha_ios: true

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
